
//REGISTRO

export const FETCH_REGISTRO_SUCCESS = 'FETCH_REGISTRO_SUCCESS'
export const FETCH_REGISTRO_ERROR = 'FETCH_REGISTRO_ERROR'

//LOGIN 

export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS'
export const FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR'
